version: '3.8'

services:
  app:
    build:
      context: ./docker/php
    container_name: chillox_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./chilox-laravel:/var/www
    command: sh -c "chmod -R 777 storage bootstrap/cache && php-fpm"  -
    networks:
      - chillox_network
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: chillox_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./chilox-laravel:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - chillox_network
    depends_on:
      - app

  db:
    image: mysql:latest
    container_name: chillox_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: chillox
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - chillox_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: chillox_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - chillox_network
    depends_on:
      - db

networks:
  chillox_network:

volumes:
  dbdata: